version: '3.8'

services:

  postgres_apijmeter:
    container_name: postgres_apijmeter_kotlin
    image: postgres:12-alpine
    ports:
      - '5431:5431'
    command: -p 5431
    environment:
      POSTGRES_USER: apijmeter
      POSTGRES_PASSWORD: apijmeter
      POSTGRES_DB: apijmeter
      PGDATA: /var/lib/postgresql/data/apijmeter/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U apijmeter" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus_apijmeter:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    restart: always

volumes:
  dbdata:
    driver: local
  prometheus_data: {}

networks:
  default:
    name: "api_jmeter_network"