server:
  port: 8080

spring:
  application:
    name: apijmeter
  flyway:
    enabled: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      properties:
        hibernate:
          format_sql: true
    properties:
      hibernate:
        # Allows Hibernate to generate SQL optimized for a particular DBMS
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Database configuration
  datasource:
    platform: postgres
    url: {SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1